<a href="https://colab.research.google.com/github/syedmahmoodiagents/NLP/blob/main/CausalMask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.tril(np.ones((4,4)))

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [ ]:
def causal_mask(seq_len):
    return torch.tril(torch.ones((seq_len, seq_len))).bool()

In [ ]:
causal_mask(4)

tensor([[ True, False, False, False],
        [ True,  True, False, False],
        [ True,  True,  True, False],
        [ True,  True,  True,  True]])

In [ ]:
np.tril(np.ones((4,4)))

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [ ]:
# scores = scores.masked_fill(causal_mask == 0, float('-inf'))

In [2]:
Q = torch.randn(1, 4, 8)  # (batch=1, seq_len=4, d_k=8)
K = torch.randn(1, 4, 8)

In [3]:
K.shape

torch.Size([1, 4, 8])

In [4]:
K.transpose(-2, -1).shape

torch.Size([1, 8, 4])

In [5]:
scores = Q @ K.transpose(-2, -1)

In [6]:
scores

tensor([[[-0.7434, -3.9019,  1.2359,  2.6410],
         [-0.6190,  0.8161, -0.1240, -2.5217],
         [ 1.8219, -0.0438,  0.0199,  2.9268],
         [ 1.4922,  1.2227,  2.4524, -0.0920]]])

In [ ]:
scores.shape

torch.Size([1, 4, 4])

In [8]:
mask = torch.tril(torch.ones(4, 4))

In [9]:
mask

tensor([[1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.]])

In [10]:
scores = scores.masked_fill(mask == 0, float('-inf'))

In [11]:
scores

tensor([[[-0.7434,    -inf,    -inf,    -inf],
         [-0.6190,  0.8161,    -inf,    -inf],
         [ 1.8219, -0.0438,  0.0199,    -inf],
         [ 1.4922,  1.2227,  2.4524, -0.0920]]])

In [ ]:
attn = torch.softmax(scores, dim=-1)

In [ ]:
attn

tensor([[[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [2.6016e-01, 7.3984e-01, 0.0000e+00, 0.0000e+00],
         [9.3012e-02, 3.1734e-01, 5.8965e-01, 0.0000e+00],
         [2.1032e-01, 7.8932e-01, 9.9995e-05, 2.5358e-04]]])

In [ ]:
import torch

In [ ]:
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
mask = torch.full((3,3), float('-inf'))

In [ ]:
mask

tensor([[-inf, -inf, -inf],
        [-inf, -inf, -inf],
        [-inf, -inf, -inf]])

In [ ]:
torch.tril(A)

tensor([[1, 0, 0],
        [4, 5, 0],
        [7, 8, 9]])

In [ ]:
torch.tril(A, diagonal=-1)

tensor([[0, 0, 0],
        [4, 0, 0],
        [7, 8, 0]])

In [ ]:
torch.triu(A)

tensor([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 9]])

In [ ]:
torch.triu(A, diagonal=-1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [0, 8, 9]])