<a href="https://colab.research.google.com/github/syedmahmoodiagents/NLP/blob/main/RNN_tf_many2one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install tensorflow --q

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [3]:
sentences = [
    "i love deep learning",
    "i love machine learning",
    "deep learning is powerful",
    "machine learning is useful",
    "i enjoy learning ai"
]

In [4]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index
vocab_size = len(word_index) + 1

print(word_index)

{'learning': 1, 'i': 2, 'love': 3, 'deep': 4, 'machine': 5, 'is': 6, 'powerful': 7, 'useful': 8, 'enjoy': 9, 'ai': 10}


In [5]:
sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

[[2, 3, 4, 1], [2, 3, 5, 1], [4, 1, 6, 7], [5, 1, 6, 8], [2, 9, 1, 10]]


In [6]:
X = []
y = []
for seq in sequences:
    for i in range(1, len(seq)):
        X.append(seq[:i])
        y.append(seq[i])

In [7]:
for a,b in zip(X, y):
    print(a,b)

[2] 3
[2, 3] 4
[2, 3, 4] 1
[2] 3
[2, 3] 5
[2, 3, 5] 1
[4] 1
[4, 1] 6
[4, 1, 6] 7
[5] 1
[5, 1] 6
[5, 1, 6] 8
[2] 9
[2, 9] 1
[2, 9, 1] 10


In [8]:
X = pad_sequences(X, padding="pre")
X = np.array(X)
y = np.array(y)

print(X)
print(y)

[[0 0 2]
 [0 2 3]
 [2 3 4]
 [0 0 2]
 [0 2 3]
 [2 3 5]
 [0 0 4]
 [0 4 1]
 [4 1 6]
 [0 0 5]
 [0 5 1]
 [5 1 6]
 [0 0 2]
 [0 2 9]
 [2 9 1]]
[ 3  4  1  3  5  1  1  6  7  1  6  8  9  1 10]


In [ ]:
model = Sequential([
    Embedding(vocab_size, 64),
    SimpleRNN(128, return_sequences=False),
    Dense(vocab_size, activation='softmax')
])

In [9]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
# return_sequences=False
# the RNN layer will only output the hidden state from the last timestep of the input sequence

In [12]:
model.fit(X, y, epochs=200)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.0000e+00 - loss: 2.3977
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.2000 - loss: 2.3484
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.3333 - loss: 2.3000
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4667 - loss: 2.2516
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.4667 - loss: 2.2024
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4667 - loss: 2.1517
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.4667 - loss: 2.0990
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4667 - loss: 2.0440
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4667 - loss: 1.9866
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 1.9271
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 1.8661
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.4000 - 

In [24]:
seq = tokenizer.texts_to_sequences(["i love"])[0]
seq = pad_sequences([seq], maxlen=X.shape[1], padding='pre')

In [25]:
pred = model.predict(seq)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
[[1.7338021e-04 2.5444916e-03 2.2073586e-04 6.2689499e-04 4.9773729e-01
  4.9782062e-01 1.1433129e-04 1.6804146e-04 6.5388245e-05 4.5212908e-04
  7.6674849e-05]]


In [26]:
np.argmax(pred)

np.int64(5)

In [13]:
word = tokenizer.index_word[np.argmax(pred)]

In [27]:
print(word)

machine
