<a href="https://colab.research.google.com/github/syedmahmoodiagents/NLP/blob/main/RNN_tf_many2many.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install tensorflow --q

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [3]:
# sentences with 11 unique words
sentences = [
    "i love deep learning",
    "i love machine learning",
    "deep learning is powerful",
    "machine learning is useful",
    "i enjoy learning ai",
    "i enjoy engineering"
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
vocab_size = len(tokenizer.word_index) + 1 # extra 1 for padding


In [4]:
vocab_size

12

In [5]:
sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

[[2, 3, 4, 1], [2, 3, 5, 1], [4, 1, 6, 8], [5, 1, 6, 9], [2, 7, 1, 10], [2, 7, 11]]


In [6]:
X = []
Y = []

for seq in sequences:
    X.append(seq[:-1])     # Input
    Y.append(seq[1:])      # Shifted Target

for a,b in zip(X,Y):
  print(a,b)

[2, 3, 4] [3, 4, 1]
[2, 3, 5] [3, 5, 1]
[4, 1, 6] [1, 6, 8]
[5, 1, 6] [1, 6, 9]
[2, 7, 1] [7, 1, 10]
[2, 7] [7, 11]


In [7]:
max_len = max(len(x) for x in X)
print(max_len)

3


In [8]:
X = pad_sequences(X, maxlen=max_len, padding='post')
Y = pad_sequences(Y, maxlen=max_len, padding='post')

In [9]:
X

array([[2, 3, 4],
       [2, 3, 5],
       [4, 1, 6],
       [5, 1, 6],
       [2, 7, 1],
       [2, 7, 0]], dtype=int32)

In [10]:
print("Input Shape :", X.shape)
print("Target Shape:", Y.shape)

Input Shape : (6, 3)
Target Shape: (6, 3)


In [11]:
# return_sequences=True
# the RNN layer outputs a sequence of hidden states,
# where each hidden state corresponds to an input in the sequence.
# This is typically used when you're stacking multiple RNN layers together,
# or when you need the output at each step

In [12]:
model = Sequential([
    Embedding(vocab_size, 64),
    SimpleRNN(128, return_sequences=True),
    Dense(vocab_size, activation='softmax')
])

In [13]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.fit(X, Y, epochs=300)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.0556 - loss: 2.4962
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.1667 - loss: 2.4608
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.3889 - loss: 2.4256
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.5000 - loss: 2.3903
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - accuracy: 0.5556 - loss: 2.3545
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.6667 - loss: 2.3177
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6667 - loss: 2.2797
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.6667 - loss: 2.2401
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.6667 - loss: 2.1988
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.6667 - loss: 2.1558
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.6667 - loss: 2.1110
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.666

In [16]:
inpt = "i love deep"

seq = tokenizer.texts_to_sequences([inpt])[0]
seq = pad_sequences([seq], maxlen=max_len, padding='post')

print(seq)

[[2 3 4]]


In [17]:
prediction = model.predict(seq, verbose=0)

In [18]:
prediction[0]

array([[6.8985618e-04, 5.2135537e-04, 1.8247949e-04, 4.9852544e-01,
        4.6555794e-04, 3.1169906e-04, 1.6824575e-04, 4.9855492e-01,
        2.7015593e-04, 1.6295402e-04, 7.6352138e-05, 7.1026108e-05],
       [1.9996465e-05, 5.5815122e-04, 5.5224336e-05, 8.7094515e-05,
        4.9838772e-01, 4.9895269e-01, 7.6935808e-05, 1.4730591e-04,
        6.1591105e-05, 2.8989190e-05, 1.4446984e-04, 1.4798432e-03],
       [6.7124449e-05, 9.9991965e-01, 9.9134589e-08, 1.2640099e-07,
        7.0685246e-08, 5.6912462e-08, 7.9733757e-09, 1.4161763e-07,
        4.2880618e-08, 8.5399358e-07, 8.5393622e-06, 3.3734509e-06]],
      dtype=float32)

In [19]:
predicted_ids = np.argmax(prediction[0], axis=-1)
print(predicted_ids)

[7 5 1]


In [20]:
predicted_words = [tokenizer.index_word.get(i, "-") for i in predicted_ids]
print(predicted_words)

['enjoy', 'machine', 'learning']


In [21]:
print("\nInput Words          :", inpt.split())
print("Predicted Next Words :", predicted_words)


Input Words          : ['i', 'love', 'deep']
Predicted Next Words : ['enjoy', 'machine', 'learning']
